version: '3.6'

services:
  
  adapter:
    build: .
    environment:
      PYTHONPATH: /code
      GRIN_URL: https://npgsdev.ars-grin.gov/GRINGlobal/GUI.asmx
    volumes:
      - ./code:/code
    tty: true